package com.university.auctionsystem.shared.protocol;

import java.io.Serializable;

public enum RequestType implements Serializable {
    REGISTER_USER,
    LOGIN_USER,
    GET_USER_PROFILE,
    UPDATE_USER_PROFILE,

    LIST_ITEM,
    GET_SELLER_ITEMS,
    UPDATE_ITEM,
    SEARCH_ITEMS,

    CREATE_AUCTION,
    GET_ACTIVE_AUCTIONS,
    GET_AUCTION_DETAILS,
    GET_MY_CREATED_AUCTIONS,
    CANCEL_UPCOMING_AUCTION,
    GET_ENDED_AUCTIONS,

    PLACE_BID,
    GET_BIDS_FOR_AUCTION,
    GET_MY_BIDS,
    GET_MY_WON_AUCTIONS,
    SEARCH_AUCTIONS,

    SEND_MESSAGE,
    GET_MY_MESSAGES,
    MARK_MESSAGE_AS_READ,

    AUCTION_UPDATE,
    OUTBID_NOTIFICATION,
    WINNER_NOTIFICATION,
    AUCTION_ENDED_SELLER_NOTIFICATION,

    GET_ALL_USERS,
    GET_ALL_AUCTIONS,

    PROCESS_PAYMENT,

    DELETE_USER,
    DELETE_AUCTION,

    PING,
    DISCONNECT
}